### ISSUE TITLE
Latest master compatible with savon2?

### ISSUE THREAD

**Issue by rngtng** [savonrb/savon-multipart#14]
I'm confused with the Readme saying "use branch 'savon2' with when running savon >= 2.0 ". I jut did, it did work with latest savon version (as of gemspec dependencu on savon 2.1). 

Instead latest savon-multipart gem just worked fine with latest. savon

So is Readme outdated and the note abount savon 2 should be removed??

**Comment by rngtng** [comment]
cool thx, can the branch `savon2` be deleted as well?

**Comment by ebeigarts** [comment]
I'm not sure if we need to remove it, maybe someone is still using that branch (`gem 'savon-multipart', github: ..., branch: 'savon2'`).

**Comment by rngtng** [comment]
hm true, good point, but I wonder what's best practice to deprecate & remove branches? I find it confusing..
