### ISSUE TITLE
Case insensitivity of multipart header regex

### ISSUE THREAD

**Issue by stevenvegt** [savonrb/savon-multipart#16]
My response header contains
Content-Type:
      - Multipart/Related;
So, the Multipart is with a capital M. Is it possible to change the regex so it is case insensitive? 

The regex is on line 33:
https://github.com/savonrb/savon-multipart/blob/master/lib/savon/multipart/response.rb#L33

I think it is to small to make a pull request, but let me know if you prefer one!

Steven

**Comment by tjarratt** [comment]
Hey @stevenvegt thanks for opening this issue. I was pretty happy to make this change, but then I remembered that HTTP headers are [not supposed to be case sensitive](http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive). 

Are you sure that's your problem? If so, you probably have a non-compliant HTTP header parser. I'm not entirely opposed to making this change, although it would be nice to add tests for it, and justify the need for it, but I'd like to ensure this is actually a real issue first.

**Comment by stevenvegt** [comment]
And this is how we learn something every day :)

The RFC states the header field names are supposed to be care-insensitive. Does this also count for the field values? (Couldn't find anything anything in the RFC)

I use Savon in my own gem which does not include a lot of other gems. I suppose this results in the default 'net/http' lib for parsing http headers?

```
gem 'savon', "~> 2"
gem 'savon-multipart'
gem 'nokogiri', "~> 1.4"

group :development do
  gem 'vcr'
  gem 'webmock'
  gem 'bundler', "~> 1.5"
  gem 'jeweler', "~> 2"
  gem 'gemfury', "~> 0"
  gem 'rspec', "~> 2"
end
```

I'm not apposed to using another http parser. Any suggestions for a low overhead parser to test with?

**Comment by tjarratt** [comment]
Oh that's a good point. I hadn't considered the values might be case sensitive. I'll have to look into this a bit more tonight. 

Sent From A Very Small Keyboard

**Comment by tjarratt** [comment]
Okay, it seems like header **values** may be case sensitive. Will be fixing this shortly.

**Comment by tjarratt** [comment]
Thanks for reporting this @stevenvegt -- and thanks for using Savon!

**Comment by stevenvegt** [comment]
Wow, that's quick! Thanks for building this great gem! :)

**Comment by tjarratt** [comment]
I really can't take much credit. @rubiii did all of the work for several years, and we've had a lot of wonderful people from the community report issues and send pull requests. I just have the honor of maintaining it now and helping keep things running smoothly. :grinning:
