### ISSUE TITLE
savon-multipart depends on Mail gem ~> 2.5.4, which has bugs

### ISSUE THREAD

**Issue by acaeti** [savonrb/savon-multipart#22]
I ran into an issue with savon-multipart and binary files that were not attachments (they appear in the mail#part body) as described here: https://stackoverflow.com/questions/43073477/ruby-writing-binary-string-7zip-to-file-file-gets-corrupted/43122970

Could savon-multipart be updated to depend on a version of Mail gem that fixes this issue?

**Comment by bew** [comment]
Can be closed, thanks to #19 ?

**Comment by acaeti** [comment]
Based on my reading of #19 , I would agree this issue can be closed.
