### ISSUE TITLE
New release on Rubygem?

### ISSUE THREAD

**Issue by bew** [savonrb/savon-multipart#24]
Hello,

I'm interested in the changes introduced by #17 & #20, the last release on rubygem doesn't have them.

Could you please make a new release on rubygem?

Thank you

**Comment by jonnyjava** [comment]
I agree! #20 can be released too with no worries (although Travis says the tests are failing I think is only a misconfiguration)

**Comment by huerlisi** [comment]
I'm using this without issues, so would very much appreciate a new gem release:-)

**Comment by bew** [comment]
@tjarratt any update on this? :pray:

**Comment by azyzio** [comment]
Hi! Is there any chance the dependency update will be merged?

**Comment by olleolleolle** [comment]
https://github.com/savonrb/savon-multipart/compare/v2.1.1...v2.1.2 has been released. 

Sorry about the #17 not making it into the CHANGELOG. I will add it there.
